# .readthedocs.yaml
version: 2

sphinx:
  configuration: source/conf.py

python:
  version: 3.10
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - sphinx-build -b html source/ build/html
