# .readthedocs.yaml
version: 2

# Sphinx 配置
sphinx:
  configuration: source/conf.py  # 指向你的 conf.py 路径

# Python 环境配置
python:
  version: 3.10  # 你本地使用的 Python 版本
  install:
    - requirements: requirements.txt  # 安装依赖，如果没有依赖也可以保留空文件

# 构建镜像
build:
  image: latest  # 使用官方最新构建镜像
