# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt  # 如果你没有这个文件，也可以新建一个空的，或者只写 path
    # - path: .   # 可选，表示安装当前仓库

sphinx:
  configuration: source/conf.py
  builder: html
