# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.10
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04   # 这里不能写 build, 必须是 ubuntu-20.04 / ubuntu-22.04 / macos / windows
